All more features on devnet scripts
XinFinOrg/XinFin-Node pull request #68
Opened 2022-08-06 17:14 UTC by liam-lai

Enhance one time script to rollback and re-create docker to fetch latest change.

2022-11-12 04:33 UTC, wjrjerome approved these changes

2023-01-18 12:22 UTC, wjrjerome approved these changes

2023-01-24 11:45 UTC, AnilChinchawale approved these changes

2023-01-24 11:46 UTC, AnilChinchawale requested changes
Can we update the correct email id, DEVNET@xinfin.com to devnet@xinfin.network?

2023-06-17 05:53 UTC, merged